### PR TITLE
Display all wikifarm hosts in the redirect banner

### PR DESCRIPTION
**Pull request by SnorlaxMonster**
Instead of storing the destination wiki's host as a tag, move it to a dedicated "destination_host" property. ~The property isn't currently used regardless, but this makes it easier to use in the future if doing so is desired.~

Now the only property that is currently used in tags is "official".

### CODE REVIEW

**Comment by KevinPayravi** [comment]
Thanks for this!

We do use destination host tags in one place in the code, to output "wiki.gg" in the redirection banner: https://github.com/KevinPayravi/indie-wiki-buddy/blob/main/scripts/content-banners.js#L187

Should also add `destination_host` to site data compilation: https://github.com/KevinPayravi/indie-wiki-buddy/blob/main/scripts/common-functions.js#L102

**Comment by SnorlaxMonster** [comment]
Ah, I should have actually checked they weren't used anywhere, rather than just assuming. I've adjusted that banner to display all wikifarm hosts (not just wiki.gg).

I've assumed that all wikifarms take the indefinite article "a" instead of "an". This is true for all of the ones currently defined (wiki.gg, Miraheze, ShoutWiki, Telepedia), but it's possible this assumption won't hold in the future. If a case of a wikifarm host whose name starts with a vowel sound were to be added in the future, I'm not sure of a good way to handle it due to the recent internationalization support added (since "a" vs "an" is an English-specific problem, and any analogous cases in other languages would have different parameters).

**Comment by KevinPayravi** [comment]
> I've assumed that all wikifarms take the indefinite article "a" instead of "an". This is true for all of the ones currently defined (wiki.gg, Miraheze, ShoutWiki, Telepedia), but it's possible this assumption won't hold in the future.

Perhaps we can change the order that platforms appear in the banner text to prevent this issue down the line. Instead of "There is a [platform] wiki covering this topic!", we can have "There is a wiki on [platform] covering this topic!"

**Review by KevinPayravi — APPROVED** [review]
Thanks for this change. I'll take a look at implementing what I suggested above.

**Comment by KevinPayravi** [comment]
Made a commit to re-word banner: https://github.com/KevinPayravi/indie-wiki-buddy/commit/51a82a169dcd97b58315220302be52f40cd4b1a7

**Comment by SnorlaxMonster** [comment]
I agree that rephrasing the banner in that way is a good idea. I had started working on a commit very similar to what you did, but then got distracted and forgot to submit it. Thanks for implementing it!

**Pull request merged**
