### PR TITLE
Support custom search engine URLS, currently SearXNG and Whoogle (#439)

### PR DESCRIPTION
**Pull request by James-McK**
Currently working on adding a setting for custom search URLS, and adds the options for them to be either SearXNG or Whoogle.

Works perfectly on Chromium, but for some reason when loading a SearXNG/Whoogle instance on Firefox, it logs a very unhelpful `undefined: undefined` instead of working. Never done anything with dynamically requesting permissions or registering content scripts before, so might just be something obvious I'm missing?

(Let me know if you think the CSS needs tweaked)

### CODE REVIEW

**Comment by KevinPayravi** [comment]
Oh wow, awesome! Thanks for doing this. I'll take a look and see if I can figure out what's going on with Firefox.

**Comment by James-McK** [comment]
No problem! I'm planning to take another look at it tomorrow to see if I can get it working. Also - is it fine that it's not compressing the synced storage for custom search engines?

**Comment by KevinPayravi** [comment]
> is it fine that it's not compressing the synced storage for custom search engines?

Yep, perfectly fine! The compression is needed due to `chrome.storage.sync` having an 8 KB limit per item, and the only two items that come close to that (prior to compression) are `wikiSettings` and `searchEngineSettings`. Though I guess one could technically reach that by adding several hundred custom search engine URLs, lol.

**Comment by KevinPayravi** [comment]
I've realized that the same `undefined: undefined` error we see in Firefox also happens when the user specifies and visits a custom BreezeWiki mirror.

**Comment by KevinPayravi** [comment]
Ah, absolute paths work on both browsers (leading forward slash):

`js: [ `/scripts/common-functions.js`, `/scripts/content-search-filtering.js` ],`

Give that a shot!

**Comment by James-McK** [comment]
Ahh, perfect! Seems like it works now, thanks!

**Review by KevinPayravi — APPROVED** [review]
Ready to include in the next update, thanks again for implementing this.

**Pull request merged**
