### PR TITLE
Poupedia no longer uses index.php

### PR DESCRIPTION
**Pull request by PretzelBubbleTea**

### CODE REVIEW

**Comment by DrWhoFan13** [comment]
...It still does use index.php, it just hides it from the URL.

**Comment by KevinPayravi** [comment]
Destination search path needs to be defined (looks like it can be either `/` or `/w/index.php`; I would lean towards the latter since it is what's shown at Special:Version.

**Comment by PretzelBubbleTea** [comment]
https://poupedia.com/Special:Version

**Comment by PretzelBubbleTea** [comment]
It uses /w/index.php

**Comment by PretzelBubbleTea** [comment]
https://github.com/KevinPayravi/indie-wiki-buddy/pull/793

**Comment by PretzelBubbleTea** [comment]
https://github.com/KevinPayravi/indie-wiki-buddy/pull/793

**Pull request closed without merging**
