### PR TITLE
Add Neoseeker wikis as redirect sources

### PR DESCRIPTION
**Pull request by SnorlaxMonster**
Neoseeker is a wikifarm with [180 wikis](https://neowiki.neoseeker.com/wiki/Special:WikiList). Although they are not especially active anymore (in the last 30 days, there have been 63 edits total across all 180 wikis), historically they were much bigger — their top wikis have thousands of pages, with 2 wikis having over 10,000 pages.

Neoseeker once [pitched themselves as an alternative to Fandom](https://neowiki.neoseeker.com/wiki/Alternative_To_Wikia), but I do not see them as being in the same category as wiki.gg or Miraheze that tries to grant wikis some kind of independent identity. For example, every Neoseeker wiki uses their proprietary [AdBird skin](https://wikiapiary.com/wiki/Skin:AdBird), for a uniform design, and does not support any other skins.

I've added all Neoseeker wikis that correspond to pre-existing entries in the list of redirects. There are several other Neoseeker wikis that do have independent counterparts that are almost certainly better quality than the Neoseeker wikis (and will almost definitionally have more activity), but may be lacking compared to the corresponding Fandom wiki (I haven't audited that), so for simplicity I've left them out for now.

I have only updated the list of redirect sources, not made any changes to other parts of the IWB UI that mention "Fandom/Fextralife". I don't necessarily think those instances all need to now also mention Neoseeker, but perhaps some of them should.

### CODE REVIEW

**Comment by KevinPayravi** [comment]
Amazing, thank you! I'll review this soon. I'd like to include this in an update I'm planning later this month that will include adding support for a few more search engines, so that users will only have to approve permission for all these domains once.

**Comment by KevinPayravi** [comment]
I'll note, another reason I support adding NeoSeeker to IWB is that the content isn't freely licensed, which effectively locks all the content to NeoSeeker and prevents migrations/forks.

**Comment by SnorlaxMonster** [comment]
Ah, I hadn't actually reviewed Neoseeker's licence, because they don't specify it in the MediaWiki API or other normal places that a licence is displayed in MediaWiki. According to [their disclaimer](https://neowiki.neoseeker.com/wiki/Disclaimer):
> All original content on Wikis are copyright Neo Era Media, Inc and subject to the [Terms of Use](http://www.neoseeker.com/info/legal.html) and [Privacy Policy](http://neowiki.neoseeker.com/wiki/Grand_Theft_Auto_-_NeoWiki:Privacy_policy) for [Neoseeker.com](http://www.neoseeker.com/).

So just like Fextralife, the host owns the copyright to all of the contibuted wiki content, making forking impossible.

**Comment by SnorlaxMonster** [comment]
I did notice that there are a lot of places in the JavaScript code that check whether URLs should be redirected by whether they include "fandom.com" or "fextralife.com", so presumably those will need to be updated in order to properly support redirecting from Neoseeker.

**Comment by KevinPayravi** [comment]
All good! I've started making those updates in the code, as well as updating the permissions in the manifest files.

**Pull request merged**
